---
- name: Enforce Cisco config baseline
  hosts: all
  gather_facts: no
  tasks:
    - name: Set hostname
      cisco.ios.ios_system:
        hostname: Router-01
    
    - name: Configure NTP
      cisco.ios.ios_ntp:
        config:
          - server: 192.168.0.1
          - source_interface: Loopback0
    
    - name: Configure SNMP community string
      cisco.ios.ios_snmp:
        community:
          name: public
          mode: ro
    
    - name: Configure logging
      cisco.ios.ios_logging:
        logging: 192.168.1.100
        level: informational
    
    - name: Configure VLANs
      cisco.ios.ios_vlan:
        vlan_id: 10
        name: Sales
        state: present
    
    - name: Save the configuration
      cisco.ios.ios_config:
        save_when: modified
