---
- name: Enforce Cisco config baseline
  hosts: all
  gather_facts: no
  tasks:
    - name: Set hostname
      cisco.ios.ios_system:
        hostname: Router-01
    
    - name: Configure NTP
      cisco.ios.ios_ntp:
        config:
          - server: 192.168.0.1
          - source_interface: Loopback0
    
    - name: Configure logging
      ios_logging:
          dest: host
          name: 172.16.0.1
          state: present
    
    - name: Configure VLANs
      cisco.ios.ios_vlan:
        vlan_id: 10
        name: Sales
        state: present
    
    - name: Save the configuration
      cisco.ios.ios_config:
        save_when: modified
