---
- name: Enforce Cisco config baseline
  hosts: all
  gather_facts: no
  tasks:
    - name: Set hostname
      cisco.ios.ios_system:
        hostname: Router-01
    
    - name: Configure NTP
      cisco.ios.ios_ntp:
        config:
          - server: 192.168.0.1
        
    - name: Save the configuration
      cisco.ios.ios_config:
        save_when: modified
